### PR TITLE
Allowing delayed events

### PR DESCRIPTION
**Pull request by jazibjohar**
This will enable enqueuing without defining the name space every time.
This should also work for scheduling tasks for instance if I want an event to occur 20 minutes after an event it can also be scheduled.

Open for suggestions and imporvements

### CODE REVIEW

**Comment by steenzout** [comment]
@jazibjohar, I'm not a developer on this project but I don't think this can be merged.

you are pointing the imports to `jazibjohar/go-resque`.

I think you need to clone your `jazibjohar/go-resque` repo to `${GOPATH}/src/github.com/kavu/go-resque`, make the changes you propose, test, push the changes to your `jazibjohar/go-resque` repo to a `pr` branch and then make the pull request from that branch.

**Comment by steenzout** [comment]
fixed reference to remote repo ^.

**Comment by kavu** [comment]
Wow. Totally missed this PR. I am sorry, @jazibjohar.

And yes, @steenzout is absolutely right — I can not merge this until package paths are correct.

**Comment by jazibjohar** [comment]
References fixed

**Pull request merged**
